### ISSUE TITLE
Custom font doesn't seem to work

### ISSUE THREAD

**Issue by rr-** [ibus/ibus#1856]
Whatever I set custom font to, it doesn't seem to be applied even after I restart the window manager:

![20160510_153900_zpx](https://cloud.githubusercontent.com/assets/1045476/15148397/57982eb4-16c5-11e6-819e-d8d89791c8b7.png)
*(please note the font size)*

I am using Linux Arch, ibus 1.5.13 with ibus-anthy, URxvt, bspwm and lxappearance.

I think this has something to do with GTK3 settings. But even after I commented out `gtk-font-name=DejaVu Sans 10` in `~/.config/gtk-3.0/settings.ini`, the issue persists.

I remember this having worked correctly before, but can't tell what led to ibus being no longer able to set the font properly.

**Comment by rr-** [comment]
I kind of worked this around with https://github.com/rr-/dotfiles/commit/00d5ba0740cdba50242b038f123a8dc71c8d61ec. This doesn't the core problem any less valid though.

**Comment by rr-** [comment]
To anyone who reads this looking for a solution to similar problems - actually, sandboxing `$XDG_CONFIG_HOME` like above is a bad idea and causes all sort of problems:

1. `ibus` tried to read its settings properly from `~/.config/ibus/dconf/user`
2. `ibus-anthy` however seemed to be updating `~/.config/dconf/user` instead (?) - well, at least it kept creating files there, despite having exported `$XDG_CONFIG_HOME`
3. Symlinking didn't seem to work (I haven't had time to test it thoroughly)
4. On top of all that, `ibus` input has stopped working in at least Firefox, which has prompted me to look for another solution

I investigated the issue further and came up with another possible approach, that rather than sandboxing entire GTK configuration (along with other applications), injects a tiny CSS rule to `~/.config/gtk-3.0/gtk.css`:


    #IBusCandidate *
    {
        font: IPAPGothic 20;
    }

(Related: https://github.com/rr-/dotfiles/commit/be029c13126f1654cf5074d083ce8c595c6a37bd)

This seems to work perfectly so far.

**Comment by fujiwarat** [comment]
Thanks for the report. I understand the issue.

> gtk-font-name=DejaVu Sans 10 in ~/.config/gtk-3.0/settings.ini, the issue persists.

If "Use custom font" on ibus-setup is disabled, I think ibus ui uses the default fonts.

I think you use GTK 3.20 or higher. The problem happens because GTK 3.20 changed all the CSS node names. ibus needs to replace "GtkLabel" to "label".

> #IBusCandidate *
> {
>     font: IPAPGothic 20;
> }

That is a good idea but ibus don't use "#IBusCandidate" only but also other UI elements so I will use "label" instead.

> rr-/dotfiles@00d5ba0

I may not understand the workaround but I think ibus ui loads gtk-settings.ini and gtk.css correctly.

>  ibus tried to read its settings properly from ~/.config/ibus/dconf/user 
> ibus-anthy however seemed to be updating ~/.config/dconf/user instead (?) 

Right. ibus core has been moved to gsettings but ibus engines still use dconf unfortunately since GSettingsList is not supported yet.
https://bugzilla.gnome.org/show_bug.cgi?id=622126

Attaching the suggested fix:
[ibus-1856-css-font.txt](https://github.com/ibus/ibus/files/286245/ibus-1856-css-font.txt)

**Comment by rr-** [comment]
@fujiwarat the patch works perfectly for GTK 3.20 (haven't tested with earlier GTK versions):

![20160527_200707_fol](https://cloud.githubusercontent.com/assets/1045476/15616943/e711dbe2-2446-11e6-929d-e0defbb56f92.png)

Also you're right, I'm using gtk3 3.20.6-1. GTK 3.20 became main version on Arch Linux in March this year: https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/gtk3

**Comment by parjanya** [comment]
Hi! I’m also using Ibus and Arch, and I can’t change the candidates font for Chinese . Where should I edit/create a .css file? Is it on `./config/gtk-3.0`? :-$

**Comment by fujiwarat** [comment]
If you use non-GNOME desktop, you should try the latest IBus.

**Comment by jidanni** [comment]
I AM USING DEBIAN SID.
THE CHINESE FONTS ARE STUCK AT SIZE 10.
THERE IS NO WAY TO CHANGE THEM.
IT IS NOT LIKE WE CAN USE THESE CAPITAL LETTERS TO SEE THEM.
PLEASE SOMEBODY FIX THIS.

**Comment by fujiwarat** [comment]
@jidanni 
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=856685

I think your issue is fixed in ibus 1.5.15 relative with issue #1879

**Comment by jidanni** [comment]
>>>>> "TF" == Takao Fujiwara <notifications@github.com> writes:

TF> I think your issue is fixed in ibus 1.5.15 relative with issue #1879

OK I will CC Debian to get 1.5.14-2 upgraded!

**Comment by Rw8671** [comment]
@rr- 
Hello, sorry if I'm a bit off topic, but I'm also using bspwm and I'm unable to get ibus-anthy to work. Could you please share your configs? Thanks.

**Comment by rr-** [comment]
@Rw8671 my configs can be found here https://github.com/rr-/dotfiles.git but you'll have to find your way around on your own :P

**Comment by Rw8671** [comment]
@rr- 
I do not know even if I look at the dot file.
Please tell me more about ibus settings.

**Comment by jchai01** [comment]
It's still not working in 2025, I have tried adding the settings to: `~/.config/gtk-3.0/gtk.css`, any solutions yet?
